---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  annotations:
    "kapp.k14s.io/change-group": "second"
    kapp.k14s.io/change-rule: upsert after upserting first
  name: mae-echo-tr
  namespace: dev
spec:
  taskRef:
    name: echo-task
